server:
  port: 80




eureka:
  client:
    register-with-eureka: true   #表示是否讲自己注册进EurekaServer 默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.158:3306/db2019?uesUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  application:
    name: order-payment-service