server:
  port: 80


eureka:
  client:
    register-with-eureka: false   #表示是否讲自己注册进EurekaServer 默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeOut: 5000   #  建立连接所用的时间，网络正常情况下，两端连接所需要时间；
  ConnecTimeOut: 5000   #

logging:
  level:
    com.jxwy.springcloud.service.OrderFeignService: debug